<?php
$dbtype='pgsql';//mysql,mssql,pgsql
$server='127.0.0.1';
$database='warehouse';
$user='warehouse';
$pass='dispatch';
$apiroot='http://127.0.0.1/dbview/api/';
$credentialServerType='pgsql';
$credentialServer='127.0.0.1';
$credentialDatabase='warehouse';
$credentialUsername='warehouse';
$credentialPassword='dispatch';
$credentialTable='credentials';
$credentialUserColumn='username';
$credentialPassColumn='password';
$credentialAdminColumn='securitylevel';
$userRO=$user;
$passRO=$pass;
?>