<?php
$dbtype='mysql';//mysql,mssql,pgsql
$server='';
$database='';
$user='';
$pass='';
$apiroot='';
$credentialServerType='mysql';
$credentialServer='';
$credentialDatabase='';
$credentialUsername='';
$credentialPassword='';
$credentialTable='';
$credentialUserColumn='';
$credentialPassColumn='';
$credentialAdminColumn='';
$userRO=$user;
$passRO=$pass;
?>